/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IDBeiwF0y7h
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function add() {
  return (
    <Card className="w-full max-w-lg">
      <CardHeader>
        <CardTitle>Service Request Form</CardTitle>
        <CardDescription>Enter the details of the service request.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="sr">SR (Service Request)</Label>
          <Input id="sr" placeholder="Enter the service request number" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="title">Title</Label>
          <Input id="title" placeholder="Enter the title of request" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="description">Description</Label>
          <Textarea id="description" placeholder="Enter the description of request" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="customer">Customer</Label>
          <Input id="customer" placeholder="Enter the customer's name" />
        </div>
      </CardContent>
      <CardFooter>
        <Button className="ml-auto">Submit</Button>
      </CardFooter>
    </Card>
  )
}
