/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zN8ogsXvxKg
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function rapidsearch() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100">
      <Card className="shadow-lg max-w-2xl mx-auto mb-8">
        <CardHeader>
          <CardTitle>Search</CardTitle>
        </CardHeader>
        <CardContent>
          <form className="flex items-center space-x-2">
            <Input className="flex-grow" placeholder="Enter search query" type="text" />
            <Button type="submit">Search</Button>
          </form>
        </CardContent>
      </Card>
      <div className="w-full max-w-2xl mx-auto bg-white shadow-lg rounded-lg overflow-hidden">
        <div className="grid grid-cols-3 gap-4 p-4">
          <div className="font-bold text-lg">Title</div>
          <div className="font-bold text-lg">Description</div>
          <div className="font-bold text-lg">Rank</div>
        </div>
        <div className="border-t border-gray-200">
          <div className="grid grid-cols-3 gap-4 p-4">
            <div>Result 1</div>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
            <div>1</div>
          </div>
          <div className="grid grid-cols-3 gap-4 p-4 border-t border-gray-200">
            <div>Result 2</div>
            <div>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</div>
            <div>2</div>
          </div>
          <div className="grid grid-cols-3 gap-4 p-4 border-t border-gray-200">
            <div>Result 3</div>
            <div>
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
              consequat.
            </div>
            <div>3</div>
          </div>
        </div>
      </div>
    </div>
  )
}
